### ISSUE TITLE
Problem registering a new user

### ISSUE THREAD

**Issue by meself001** [lasircc/las-docker#1]
So, I can log in as the administrator and lasmanager via the LAS front page, but when I request to register a new user I get an internal Apache error. This is what I get in the browser:

### BEGIN ####
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.18 (Ubuntu) Server at taurus--csx.grid.private.cam.ac.uk Port 443
### END ###

and this is what I get at the console where I run the "docker-composer up" command (but with passwords blanked out):

las                   | [Mon Feb 19 16:13:09.019799 2018] [wsgi:error] [pid 44:tid 140417189160704] {'MONGO_INITDB_ROOT_PASSWORD': 'XXXXXX', 'EMAIL_ADMIN_PASSWORD': 'XXXXXX', 'MYSQL_ROOT_PASSWORD': 'Las@Irc2016', 'EMAIL_ADMIN_USER': 'cruk_test@outlook.com', 'MYSQL_USER': 'las', 'ADMIN_PASSWORD': 'XXXXXX', 'HOME': '/var/www', 'PATH': '/virtualenvs/venvdj1.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'MONGO_LOG_DIR': '/dev/null', 'PMA_ARBITRARY': '1', 'APACHE_RUN_DIR': '/var/run/apache2', 'APACHE_LOG_DIR': '/var/log/apache2', 'APACHE_RUN_GROUP': 'www-data', 'EMAIL_HOST': 'smtp.live.com', 'MYSQL_PASSWORD': 'XXXXXX', 'WORKON_HOME': '/virtualenvs', 'MYSQL_HOST': 'localhost', 'APACHE_PID_FILE': '/var/run/apache2/apache2.pid', 'MONGO_DATA_DIR': '/data/db', 'HOST': 'taurus--csx.grid.private.cam.ac.uk', 'APACHE_LOCK_DIR': '/var/lock/apache2', 'MYSQL_PORT': '3306', 'EMAIL_USE_TLS': 'True', 'EMAIL_PORT': '587', 'LANG': 'C', 'NEO4J_AUTH': 'none', 'DB_PASS': 'XXXXXX', 'APACHE_RUN_USER': 'www-data', 'HOSTNAME': 'c75b6817dfbd', 'PWD': '/', 'DJANGO_SETTINGS_MODULE': 'LASAuthServer.settings', 'EXTENSION_SCRIPT': '/neo4j-data/neo4j-init.sh', 'MONGO_INITDB_ROOT_USERNAME': 'las'}
las                   | [Mon Feb 19 16:13:09.286997 2018] [wsgi:error] [pid 44:tid 140417189160704] {'MONGO_INITDB_ROOT_PASSWORD': 'XXXXXX', 'EMAIL_ADMIN_PASSWORD': 'XXXXXX', 'MYSQL_ROOT_PASSWORD': 'XXXXXX', 'EMAIL_ADMIN_USER': 'cruk_test@outlook.com', 'MYSQL_USER': 'las', 'ADMIN_PASSWORD': 'XXXXXX', 'HOME': '/var/www', 'PATH': '/virtualenvs/venvdj1.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'MONGO_LOG_DIR': '/dev/null', 'PMA_ARBITRARY': '1', 'TZ': 'Europe/Rome', 'APACHE_RUN_DIR': '/var/run/apache2', 'APACHE_LOG_DIR': '/var/log/apache2', 'APACHE_RUN_GROUP': 'www-data', 'EMAIL_HOST': 'smtp.live.com', 'MYSQL_PASSWORD': 'XXXXX', 'WORKON_HOME': '/virtualenvs', 'MYSQL_HOST': 'localhost', 'APACHE_PID_FILE': '/var/run/apache2/apache2.pid', 'MONGO_DATA_DIR': '/data/db', 'HOST': 'taurus--csx.grid.private.cam.ac.uk', 'APACHE_LOCK_DIR': '/var/lock/apache2', 'MYSQL_PORT': '3306', 'EMAIL_USE_TLS': 'True', 'EMAIL_PORT': '587', 'LANG': 'C', 'NEO4J_AUTH': 'none', 'DB_PASS': 'Las@Irc2016', 'APACHE_RUN_USER': 'www-data', 'HOSTNAME': 'c75b6817dfbd', 'PWD': '/', 'DJANGO_SETTINGS_MODULE': 'LASAuthServer.settings', 'EXTENSION_SCRIPT': '/neo4j-data/neo4j-init.sh', 'MONGO_INITDB_ROOT_USERNAME': 'las'}
las                   | [Mon Feb 19 16:13:09.856478 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848] mod_wsgi (pid=44): Exception occurred processing WSGI script '/srv/www/LASAuthServer/apache/django.wsgi'.
las                   | [Mon Feb 19 16:13:09.856535 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848] Traceback (most recent call last):
las                   | [Mon Feb 19 16:13:09.856566 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/srv/www/LASAuthServer/apache/django.wsgi", line 46, in application
las                   | [Mon Feb 19 16:13:09.856671 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     return _application(environ, start_response)
las                   | [Mon Feb 19 16:13:09.856692 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
las                   | [Mon Feb 19 16:13:09.856855 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     response = self.get_response(request)
las                   | [Mon Feb 19 16:13:09.856876 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/core/handlers/base.py", line 179, in get_response
las                   | [Mon Feb 19 16:13:09.856946 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
las                   | [Mon Feb 19 16:13:09.856979 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/core/handlers/base.py", line 228, in handle_uncaught_exception
las                   | [Mon Feb 19 16:13:09.857010 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     return callback(request, **param_dict)
las                   | [Mon Feb 19 16:13:09.857028 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
las                   | [Mon Feb 19 16:13:09.857139 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     response = view_func(request, *args, **kwargs)
las                   | [Mon Feb 19 16:13:09.857159 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/views/defaults.py", line 33, in server_error
las                   | [Mon Feb 19 16:13:09.857263 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     return http.HttpResponseServerError(t.render(Context({})))
las                   | [Mon Feb 19 16:13:09.857283 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/template/base.py", line 140, in render
las                   | [Mon Feb 19 16:13:09.857316 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     return self._render(context)
las                   | [Mon Feb 19 16:13:09.857332 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
las                   | [Mon Feb 19 16:13:09.857361 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     return self.nodelist.render(context)
las                   | [Mon Feb 19 16:13:09.857377 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/template/base.py", line 823, in render
las                   | [Mon Feb 19 16:13:09.857405 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     bit = self.render_node(node, context)
las                   | [Mon Feb 19 16:13:09.857421 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/template/base.py", line 837, in render_node
las                   | [Mon Feb 19 16:13:09.857449 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     return node.render(context)
las                   | [Mon Feb 19 16:13:09.857465 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
las                   | [Mon Feb 19 16:13:09.857494 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     compiled_parent = self.get_parent(context)
las                   | [Mon Feb 19 16:13:09.857510 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
las                   | [Mon Feb 19 16:13:09.857539 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     return get_template(parent)
las                   | [Mon Feb 19 16:13:09.857554 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/template/loader.py", line 145, in get_template
las                   | [Mon Feb 19 16:13:09.857583 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     template, origin = find_template(template_name)
las                   | [Mon Feb 19 16:13:09.857598 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]   File "/virtualenvs/venvdj1.4/lib/python2.7/site-packages/django/template/loader.py", line 138, in find_template
las                   | [Mon Feb 19 16:13:09.857626 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848]     raise TemplateDoesNotExist(name)
las                   | [Mon Feb 19 16:13:09.857649 2018] [wsgi:error] [pid 44:tid 140417189160704] [remote 131.111.56.24:10848] TemplateDoesNotExist: admin/base_site.html

Mark

**Comment by alefiori82** [comment]
We updated the LASAuth module. We tested it and it works fine. Please try again after also updating the lasauthserver database with the new dump.
